### ISSUE TITLE
Supercronic is not running jobs

### ISSUE THREAD

**Issue by coldpar** [aptible/supercronic#112]
Hi Team,

I just started using supercronic within some containers, we have some jobs that taking some time to finish like about 20 minutes and when supercronic start this kind of job it is stuck waiting for it to finish and escape the following jobs.

Example:
```
Job 1: 14 5 * * * /scripts/OneLongPing
Job 2: */5 * * * * echo "every 5 minutes" > /dev/null
```

Job 1 will be executed at 05:14 and will take 20 minutes to finish, supercronic is not executing Job 2 and stuck with the message:
`level=info msg="waiting for jobs to finish" `

is there any way to change this behavior ?

Thanks in advance

**Comment by ChristophKronberger** [comment]
Have you ever tried to add a "&" to your command, so it may be executed in background.
Job 1: 14 5 * * * /scripts/OneLongPing &
Job 2: */5 * * * * echo "every 5 minutes" > /dev/null

**Comment by dimanzver** [comment]
Is there a solution?

**Comment by UserNotFound** [comment]
Please reopen if someone can provide a crontab (or better yet, a whole Dockerfile) that can reproduce the issue.

**Comment by dimanzver** [comment]
Fixed with `shareProcessNamespace` setting.
