### ISSUE TITLE
space issue while exporting env var SUPERCRONIC_SHA1SUM

### ISSUE THREAD

**Issue by lokeshrajai** [aptible/supercronic#113]
<img width="1161" alt="Screenshot 2022-09-18 at 7 08 39 PM" src="https://user-images.githubusercontent.com/24380748/190905416-7c355723-57ee-4080-82cd-400eaddb6b85.png">

the space in 

SUPERCRONIC_SHA1SUM= d7f4c0886eb85249ad05ed592902fa6865bb9d70

causes issue while export env var

sha1sum: 'standard input': no properly formatted SHA1 checksum lines found

from the release page, installation instructions

https://github.com/aptible/supercronic/releases#:~:text=SUPERCRONIC_SHA1SUM%3D%20d7f4c0886eb85249ad05ed592902fa6865bb9d70

**Comment by capelio** [comment]
I was caught by this as well. It's a small thing, but it definitely breaks the installation flow when following all the official documentation and attempting to use the `Dockerfile` instructions from the latest release page.

**Comment by bradgessler** [comment]
Yeah I ran into this copy & pasting from the latest release notes https://github.com/aptible/supercronic/releases/tag/v0.2.1

My error was much less clear though, so it took me a while to chase this down.

Another suggestion I have for the release notes; you might consider adding a comment above each copy pasta block that reads like this:

```Dockerfile
```

**Comment by UserNotFound** [comment]
Thanks everyone, the release notes have been updates to omit the space, and future release notes ([such as this one](https://github.com/aptible/supercronic/releases/tag/v0.2.2)) will include the note @bradgessler suggested.
