### ISSUE TITLE
Allow to specify sentry envionment and release

### ISSUE THREAD

**Issue by lucagouty** [aptible/supercronic#114]
Hi there,

Today we can set Sentry DSN but it would be nice to also be able to set Sentry [environment](https://docs.sentry.io/product/sentry-basics/environments/) and [release](https://docs.sentry.io/product/releases/).

It seems `logrus_sentry` allows it : 
https://github.com/evalphobia/logrus_sentry/issues/22
https://github.com/evalphobia/logrus_sentry/pull/26

To be consistent with `-sentry-dsn` and `SENTRY_DSN`, I guess it should be done for `SENTRY_ENVIRONMENT`/`SENTRY_RELEASE` env variables and `-sentry-environment`/`-sentry-release` CLI arguments.

Thanks for this project btw, it's awesome ❤️

**Comment by imperiuse** [comment]
Hi all, I have resolved this issue. Could anyone please merge it?

fyi @lucagouty @UserNotFound

**Comment by lucagouty** [comment]
thanks guys it works great 🚀
