### ISSUE TITLE
Multiple CVE:s with severity level High due to use of Go-lang version 1.18.3.

### ISSUE THREAD

**Issue by jorander** [aptible/supercronic#120]
There are quite a few CVE:s with severity level High for Go-lang version [1.18.3](https://go.dev/doc/devel/release#go1.18) (released 2022-06-01). In order to resolve them an upgrade to version 1.18.9 (released 2022-12-06) would be needed.

**Comment by UserNotFound** [comment]
[Release v0.2.2](https://github.com/aptible/supercronic/releases/tag/v0.2.2) was build with the latest 1.18.x version, which you can see in the [build logs here](https://github.com/aptible/supercronic/actions/runs/4256412480/jobs/7405265039#step:2:9) is 1.18.10

**Comment by jorander** [comment]
Many thanks!
