### ISSUE TITLE
Vulnerabilities reported against "golang.org/x/sys/unix".

### ISSUE THREAD

**Issue by mkielar** [aptible/supercronic#126]
### Context
In one of our projects we're using `pact-broker` docker image, which uses `supersonic`. We're re-packaging the `pact-broker` image to install some additional tooling (security / monitoring / etc) and harden the image. Then we scan that image with `snyk.io`.

# The problem
`snyk.io` reports vulnerability in `v0.0.0-20220615213510-4f61da869c0c` version of `golang.org/x/sys/unix` which is a transitive vulnerability of `supersonic`. The detailed snyk report looks like this:

```
✗ Medium severity vulnerability found in golang.org/x/sys/unix
  Description: Incorrect Privilege Assignment
  Info: https://security.snyk.io/vuln/SNYK-GOLANG-GOLANGORGXSYSUNIX-3310442
  Introduced through: golang.org/x/sys/unix@v0.0.0-20220615213510-4f61da869c0c
  From: golang.org/x/sys/unix@v0.0.0-20220615213510-4f61da869c0c
  Fixed in: 0.1.0

Organization:      [REDACTED]
Package manager:   gomodules
Target file:       /usr/local/bin/supercronic-linux-amd64
Project name:      github.com/aptible/supercronic
Docker image:      [REDACTED].pact-broker
Licenses:          enabled
```

# Proposed solution
It seems that upgrading `golang.org/x/sys/unix` to `0.1.0` fixes the vulnerability.

**Comment by UserNotFound** [comment]
[v0.2.24](https://github.com/aptible/supercronic/releases/tag/v0.2.24)
