### ISSUE TITLE
CVEs in golang/stdlib

### ISSUE THREAD

**Issue by K2ouMais** [aptible/supercronic#128]
Hello everyone,

it seems that there are again some CVEs showing up in the golang stdlib.

![Supercronic_CVEs](https://github.com/aptible/supercronic/assets/52510455/17e0cc79-f29d-4a33-b3be-021e663e281b)

Probably golang hast to be updated again.

Thank you

**Comment by liorhasson** [comment]
Hey,

Any ETA for this one?

**Comment by mattwiese-aptible** [comment]
Hi @K2ouMais & @liorhasson - Thanks for raising this. We are aware of the vulnerabilities and have prioritized rolling out a patch this sprint. We've assessed and concluded that Supercronic's published binary contains no code paths impacted by these Go vulnerabilities. If you've substantially modified the code such that the CVEs do impact you, you may rebuild your binary at any time with the latest Go version.

**Comment by K2ouMais** [comment]
Thank you for providing a patch.

I have not changed the code in anyway, so it seems that this will not impact me in any way.

I would love to rebuild the binary with the newest go version, but I have absolutely no skills in go to do this.

**Comment by UserNotFound** [comment]
https://github.com/aptible/supercronic/releases/tag/v0.2.25
