### ISSUE TITLE
Format and Doc question

### ISSUE THREAD

**Issue by ipflowss** [aptible/supercronic#137]
Hi there,

Can somebody please explain what the time measurement or each * entry below?  Can the answer to my question be reflected in the main README.md .

*/2 * * * * * * ls 2>/dev/null

Cheers

**Comment by UserNotFound** [comment]
Hello,  the README for Supercronic already links to the library used for parsing the crontrab under the heading "[Crontab format](https://github.com/aptible/supercronic/tree/master#crontab-format)":

>First, Supercronic supports second-resolution schedules: Under the hood, Supercronic uses [the cronexpr package](https://github.com/aptible/supercronic/tree/master/cronexpr), so refer to its documentation to know exactly what you can do.

There you will find the following definition of the format: 

```
Field name     Mandatory?   Allowed values    Allowed special characters
----------     ----------   --------------    --------------------------
Seconds        No           0-59              * / , -
Minutes        Yes          0-59              * / , -
Hours          Yes          0-23              * / , -
Day of month   Yes          1-31              * / , - L W
Month          Yes          1-12 or JAN-DEC   * / , -
Day of week    Yes          0-6 or SUN-SAT    * / , - L #
Year           No           1970–2099         * / , -
```
