### ISSUE TITLE
remove warning for longer jobs

### ISSUE THREAD

**Issue by yayitswei** [aptible/supercronic#16]
Thanks for making supercronic! I've found it useful so far.

One issue I'd like to fix in my setup is that after installing supercronic, my messages are now showing up in `stderr` instad of `stdout`. Any ideas why this might be happening?

**Comment by krallin** [comment]
Hi there,

Supercronic itself logs to stderr, so it's expected that you'd see output there. Note that the log output from Supercronic actually includes the stream (stdout / stderr) that sent a message:

```
2017-10-03T07:41:57.809Z [papabear-cmd 74a03c8c8529]: time="2017-10-03T07:41:57Z" level=info msg="I, [2017-10-03T07:41:56.893591 #4264]  INFO -- : Some message!" channel=stdout iteration=3131 job.command="rake doit" job.position=3 job.schedule="*/5 * * * *"
```

(see `channel=stdout` above)

Depending on how you're processing / storing these logs, you might also want to enable the JSON output mode, which is of course easier to post-process.

Cheers,

**Comment by yayitswei** [comment]
Thanks for the reply, I'll look into JSON output mode. Just curious, what's the reason for logging to stderr instead of stdout?

**Comment by krallin** [comment]
`stdout` is typically for the _output_ of commands, whereas `stderr`  is typically used for logging / informational message, so it typically makes sense to route logs to `stderr`. That said, Supercronic doesn't really have any meaningful output to speak of, so I guess one could go both ways.... Supercronic happens to use `stderr`.
