### ISSUE TITLE
Why I need CURL?

### ISSUE THREAD

**Issue by derskythe** [aptible/supercronic#160]
Hi, thanks for your software.
Your guide says that I need curl, but I can use such Dockerfile without any additional software:

```Dockerfile
# syntax=docker/dockerfile:1

ARG MY_USER_NAME="me"
ARG MY_USER_GROUP_NAME="mygroup"
ARG SUPERSONIC_VERSION="v0.2.30"
ARG SUPERSONIC_SHA256="sha256:55f3a65b6ef29856d948230a96448f6ec7376d39fca367fae49d2512167e29e5"

ADD --checksum=${SUPERSONIC_SHA256} \
--chown=${MY_USER_NAME}:${MY_USER_GROUP_NAME} --chmod=755 \
    "https://github.com/aptible/supercronic/releases/download/${SUPERSONIC_VERSION}/supercronic-linux-amd64" \
    /usr/bin/supercronic
```

**Comment by UserNotFound** [comment]
Hello, `curl` is used in the provided `RUN` instruction for downloading the binary.  You're of course welcome to install it the way you demonstrated, but our documented instructions will at the moment continue to use `curl` for compatibility across all Docker daemon versions and configurations.  (Buildkit is required for the [Custom Dockerfile syntax](https://docs.docker.com/build/dockerfile/frontend/) you shared, and I don't believe the --checksum and --chmod options are available in all [currently supported versions of Docker Engine](https://endoflife.date/docker-engine) )
