### ISSUE TITLE
Allow to configure the cron jobs through ENV variables

### ISSUE THREAD

**Issue by Cajga** [aptible/supercronic#28]
Hi,

First of all thanks for the software it is really useful sometimes!

It would be really great if we could define the cron entries via environment variables so we do not need to have static files in our container (or mount the cron file from the container host).
To workaround this I am using [confd](https://github.com/kelseyhightower/confd) and using environment variable as source for my cron file.

Thanks,
Balazs

**Comment by krallin** [comment]
Writing out the configuration to a file using a separate tool (such as `confd`, or simply a shell entrypoint that calls `printf`) is the preferred solution here: they're fairly easy to compose with Supercronic and I don't see a compelling reason why that functionality should be built into Supercronic itself.

**Comment by Cajga** [comment]
Hi @krallin,

My 5 cents: Supercronic is designed to run inside docker. Following the best practices and receiving configuration through environment variables would make people's life much more simple. You are absolutely right about there are other solution to achieve this goal like confd but those have been invented to make legacy applications work inside containers.

Supercronic is really cool and this feature would make it even better. :)

**Comment by krallin** [comment]
@Cajga Thanks for your feedback; That said, I favor building tools that are easily composable and don't offer superfluous configuration options.

Every time you add an option (e.g. "provide a crontab OR pass it through the environment), that creates mental overhead for new users: _"should i use a crontab, or should I use the environment? what's the best practice? well I guess, it depends on my use case? is my crontab configuration? I'm not sure."_.

By providing a single way to do it ("pass a crontab"), users with a simple use case (which are always a majority of users) have a simple way to achieve it. By making the tool composable, users with a more complex use case (like yours, where you apparently need the crontab to be configuration) can layer on another tool to achieve their use case.

This isn't about about legacy or best practice: it's about simplicity.
