### ISSUE TITLE
How to restart supercronic / refresh list of jobs

### ISSUE THREAD

**Issue by danielszwarc** [aptible/supercronic#33]
I start supercronic with: `supercronic /app/config/crontab`
In some situations I need to add some jobs to  `/app/config/crontab` (after supercronic startup).
But new jobs are not recognized by supercronic.
Is there way to restart supercronic / refresh list of jobs?

**Comment by krallin** [comment]
Currently; there is no provision in Supercronic to reload jobs.

If you'd like to update your crontab, you'll need to stop Supercronic (you can gracefully stop Supercronic by sending SIGTERM or SIGINT), then start it again.
