### ISSUE TITLE
how to add job to supercronic docker?

### ISSUE THREAD

**Issue by ronaldwu** [aptible/supercronic#37]
I used crontab in my original machine, I use crontab -e to edit job list.
but after I use supercronic docker, I don't know how to do that. this docker cannot use command "docker exec -ti supercronic /bin/bash" to access this docker and use crontab -e to edit job list.

what should I do, I have go through the supercronic readme.md, I did not found any introduction about this. could you help me about this?

Thanks,
Ronald

**Comment by krallin** [comment]
You should embed your crontab into your container (using the `ADD` or `COPY` instructions in your Dockerfile), then point Supercronic at the crontab.

You can generate the crontab using whatever tool you want, but ultimately the crontab is just a text file (there are some examples used in Supercronic's tests here: https://github.com/aptible/supercronic/tree/master/integration). You need to generate such a text file somehow, and point Supercronic to it.

---

As an aside, you shouldn't edit the crontab once Supercronic's already running. This won't work as Supercronic won't reload it at that point.
