### ISSUE TITLE
Any plan to seperate stdout/stderr log?

### ISSUE THREAD

**Issue by katsew** [aptible/supercronic#40]
Hi,
Thanks for making this great tool!

Is there any plan to add separate stdout/stderr log option to supercronic?
I saw [this closed issue](https://github.com/aptible/supercronic/issues/16), and I understand why supercronic logs all log to stderr.

But I use supercronic with stackdriver logging, and info logs shows as an error, and very annoying...

**Comment by krallin** [comment]
There are no such plans, no.

This should be fairly trivial to add if you wanted to make that change yourself (add a new flag in `main`, and call `logrus.SetOutput(os.Stdout)` if set).
