### ISSUE TITLE
musl support

### ISSUE THREAD

**Issue by jaysonsantos** [aptible/supercronic#47]
Hey there, any chance to get releases also with musl support? Otherwise, this cannot be used in images like alpine.
Thank you!

**Comment by krallin** [comment]
Thanks for the reporting this problem! The Supercronic binaries we distribute are intended to be static binaries. That is, they shouldn't depend on libc at all, so it shouldn't if your libc is glibc, musl (or whatever else for that matter).

However, it turns that when we introduced Sentry support in #45, we pulled in Go's network support, which by default, causes Go to build a dynamic library that links to libc. This resulted in our binaries no longer being static.

Go can be configured to not link to C code at all, which should provide us with static binaries again. I made this change in #49, and added a regression test in CI to make sure we continue building static binaries going forward.

**Comment by krallin** [comment]
v0.1.8 was released and fixes this problem. Thanks again for letting us know :)

**Comment by jaysonsantos** [comment]
Cool, thank you!
