### ISSUE TITLE
 How to suppress printing of crontab command each time supercronic finishes a job

### ISSUE THREAD

**Issue by davidghiurco** [aptible/supercronic#53]
Hi there. I have a containerized application which runs about 15 crontabs on a "each-minute" cron schedule.

I started using supercronic because I did not want to have to run crond as a super-user. That's a security risk which my organization needed me to find a workaround for. Supercronic to the rescue!

Supercronic's feature set is so much better than crond. So much so, that it's a bit too good for me :) 

The jobs that supercronic is running are of the form:
"${CRON_SCHEDULE} timeout -t ${timeout_seconds} java ${jvm_options}  
-Daccess.key.id=${ACCESS_KEY_ID}
-Daccess.key.secret=${ACCESS_KEY_SECRET}
-jar ${JAR} 
${app_args} > /proc/1/fd/1 2>/proc/1/fd/2"

Our application containers forward logs to a centralized logging system. 

The problem here is that there is sensitive information (AWS access keys and secrets) being passed as properties to the application. (Yes I know, I can do it with environment variables. Long story short, that will take a lot of work due to application logic requirements). These credentials are then logged in plaintext in our centralized logging system because supercronic will print them out as part of the command it just finished executing.

Is there an easy way I could disable supercronic from logging those commands which will print my credentials in plaintext .... but still leave the logs of the Java application unchanged?

**Comment by davidghiurco** [comment]
Figured it out:

`
supercronic ${crontabfile} > /dev/null 2>&1
`
does the trick

**Comment by UserNotFound** [comment]
Hi David, suppressing _all_ output from supercronic is likely to make troubleshooting much more difficult in the future, and if/when you toggle this back off, you'll reveal/log your secrets in the command again.

I would suggest having cron run a shell script, so that it logs only "job.sh", and not the full java command. In your crontab: ` "${CRON_SCHEDULE} job.sh`

And job.sh:

```
#/bin/sh
exec "${CRON_SCHEDULE} timeout -t ${timeout_seconds} java ${jvm_options} \
-Daccess.key.id=${ACCESS_KEY_ID} \
-Daccess.key.secret=${ACCESS_KEY_SECRET} \
-jar ${JAR} \
${app_args} > /proc/1/fd/1 2>/proc/1/fd/2
```
