### ISSUE TITLE
Color escape sequences are being quoted/escaped on Docker logs

### ISSUE THREAD

**Issue by goetzc** [aptible/supercronic#55]
Running Supercronic directly in a Bash shell shows colors, but when inspecting `docker logs`,  the Supercronic output is quoted or escaped which prevents showing the actual colors. 

Compared to other Cron implementations like the [Debian](https://packages.debian.org/buster/cron)'s default [Cron](https://ftp.isc.org/isc/cron/) implementation which doesn't quote/escape the output and shows the colors, whenever called directly from the shell or from `docker logs`. 

This is the Supercronic output from within Bash inside Docker:
![image](https://user-images.githubusercontent.com/2220440/66957553-13a02380-f02c-11e9-9de1-0c5a63f7b416.png)

Output from `docker logs` when using Supercronic:
`\x1b[1m\x1b[35m (0.5ms)\x1b[0m  BEGIN"`
![image](https://user-images.githubusercontent.com/2220440/66957675-477b4900-f02c-11e9-8fea-37be87c8a113.png)

Output from `docker logs` when using Debian's Cron package:
![image](https://user-images.githubusercontent.com/2220440/66957959-d4be9d80-f02c-11e9-9881-1fc13ff96e91.png)

**Comment by krallin** [comment]
What's happening here is that Supercronic reads the log of your underlying program then emits it back (those are the colors that are mangled here, not Supercronic's own log coloring). I'd suggest turning off log coloring in the jobs you run in your  crontab.

That said, if you do want the colors and don't care to have Supercronic wrap your logging, then I think the right solution would be to just let you turn off the log wrapping. I'll put up a PR for this.

**Comment by goetzc** [comment]
That is nice and useful, thank you @krallin!
