### ISSUE TITLE
Disable supercronic logs, or store them to file

### ISSUE THREAD

**Issue by icy** [aptible/supercronic#61]
Hi,

supercronic has logs but it's creating a lot of confusion with my application logs. I want to see my application logs, not supercronic. Is there any way to turn off the tool logging feature?

Thanks

**Comment by krallin** [comment]
Can you give an exampel of the logs you are seeing right now, and what you'd like to see instead?

**Comment by icy** [comment]
@krallin Never mind, there is another issue (https://github.com/aptible/supercronic/issues/62) and because of that I can't use supercronic at the moment. Thanks anyway.
