### ISSUE TITLE
[enhancement] add supercronic docker image to docker hub

### ISSUE THREAD

**Issue by dorsany** [aptible/supercronic#70]
it will be awesome to see in [docker hub](https://hub.docker.com/) the official docker image of `supercronic`.

any chance that it will happen?

**Comment by krallin** [comment]
Kinda unlikely — Supercronic isn't really a base you build on, it's something you add to an existing image to be able to run cron there. I think providing a base image encourages people to use this the wrong way, TBH.

**Comment by dorsany** [comment]
Hi @krallin , it's still seems that can be relevant by using the Supercronic in k8s as a side car container which can mount crontab file and other scripts by using configmaps.
But thanks anyway for your fast response!
