### ISSUE TITLE
Please use 9746 as a standard port for prometheus metrics

### ISSUE THREAD

**Issue by dex4er** [aptible/supercronic#74]
See https://github.com/prometheus/prometheus/wiki/Default-port-allocations

Thanks!

**Comment by hartwork** [comment]
Given that `-prometheus-listen-address string` currenty requires a `host:port` kind of value, I think a backwards-compatible way would be to turn that into `host[:port]`, use 9746 for a default and mention default port 9746 in the related description.

**Comment by krallin** [comment]
> Given that -prometheus-listen-address string currently requires a host:port kind of value, I think a backwards-compatible way would be to turn that into host[:port], use 9746 for a default and mention default port 9746 in the related description.

Yeah, I think that's the right way to do it. I sent #81 for this.
