### ISSUE TITLE
Readme still links to replaced gorhill/cronexpr (rather than krallin/cronexpr)

### ISSUE THREAD

**Issue by hartwork** [aptible/supercronic#75]
Hi!

I stumbled upon an out of date link in the readme. It says https://github.com/gorhill/cronexpr but it should probably be https://github.com/krallin/cronexpr with `krallin`. Commit 6a0e41f4ca20481f19fe0d6b015603731378c923 made the related change. Fixing the link will save the next person wondering if supercronic depends on code that is marked as archived or not.

Best, Sebastian

**Comment by hartwork** [comment]
Any thoughts?

**Comment by hartwork** [comment]
@fancyremarker do you have a minute?

**Comment by krallin** [comment]
I updated the README

**Comment by hartwork** [comment]
Thank you!
