### ISSUE TITLE
Error running command: signal: killed

### ISSUE THREAD

**Issue by bjsmiley** [aptible/supercronic#87]
Hello,

testing locally everything is running fine however once supercronic is started in k8s, I get this error message every minute:

`level=error msg="error running command: signal: killed" iteration=6 job.command="dotnet /app/myapp.dll > /proc/1/fd/1 2> /proc/1/fd/2" job.position=1 job.schedule="* * * * *"`

**Comment by krallin** [comment]
This means something is killing your program. It’s not something
Supercronic does or control

A common thing that kills your programs is using too much memory.

Check if perhaps there is anything in dmesg, or review how you enforce
memory limits.

Hope this helps!

**Comment by bjsmiley** [comment]
That was exactly it! thanks for the quick reply 
👋
