### ISSUE TITLE
Schedule job isn't started because of defunct zombie process

### ISSUE THREAD

**Issue by reevelau** [aptible/supercronic#88]
I was trying to run Magento schedule task with supercronic. But sometime the schedule job isn't trigger because previous job doesn't end. Running ```ps ufx``` shows that supercronic is waiting for a zombie process to exit.

```
> ps ufx
www-data   117  0.0  0.0 713884  7836 ?        Sl   13:49   0:00  \_ supercronic -debug /etc/cron.d/magento2-cron
www-data   699  0.0  0.0      0     0 ?        Z    13:52   0:00      \_ [sh] <defunct>
```

Here is my the content of /etc/cron.d/magento2-cron

```
* * * * * /usr/local/bin/php -d memory_limit=-1 /var/www/html/bin/magento cron:run 2>&1
```

**Comment by cksharma11** [comment]
Any updates on this?

**Comment by asansonios** [comment]
@cksharma11 I'm having the same issue for a different type of task .I'm working around this at the moment by using the timeout command to kill the job if it takes way longer than it should. That will then allow supercronic to start it at the next iteration. eg something like:

```
# Kill after 30 minutes. https://github.com/aptible/supercronic/issues/88
* * * * * timeout 30m /usr/local/bin/php -d memory_limit=-1 /var/www/html/bin/magento cron:run 2>&1
```

https://www.tecmint.com/run-linux-command-with-time-limit-and-timeout/

**Comment by dimanzver** [comment]
Any updates?

**Comment by mehrdad-op** [comment]
I have the same issue, with the PHP script.
do we have any update regarding this issue?

**Comment by dimanzver** [comment]
@mehrdad-op `shareProcessNamespace` solved it for me

**Comment by mehrdad-op** [comment]
`shareProcessNamespace `
> When process namespace sharing is enabled, processes in a container are visible to all other containers in the same pod.

I do not see how this can help me, because the zombie processes are/created in my single container.

**Comment by dimanzver** [comment]
@mehrdad-op I have single container too, but `shareProcessNamespace` solved my problem. Read https://opendev.org/airship/promenade/commit/0ffde4162ecb7539fe505840c3e4fdd4e750deb0
https://cloud.google.com/architecture/best-practices-for-building-containers#solution_2_enable_process_namespace_sharing_in_kubernetes

**Comment by qianlongzt** [comment]
Zombie processes occur under the following conditions:

1. Supercronic is the PID 1.
2. Task process A exits, leaving behind child process B.
3. Process B's parent becomes Supercronic (PID 1).
4. Supercronic does not clean up process B.

There are two ways to fix this:

1. Supercronic cleans up process B.
2. Process A cleans up process B before exiting.

https://stackoverflow.com/questions/17236630/what-happens-after-the-parent-of-zombie-process-terminates

https://github.com/ramr/go-reaper

**Comment by UserNotFound** [comment]
https://github.com/aptible/supercronic/releases/tag/v0.2.31

**Comment by mehrdad-op** [comment]
Thank you @qianlongzt and @UserNotFound  this release fixed my issue. 🙌
